import Head from "next/head";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import VideoPlayer from "@/components/VideoPlayer";
import "@castlabs/prestoplay/clpp.styles.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js with PRESTOplay player</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/mux.js@5.14.1/dist/mux.js" async></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.banner}>
            <a href="https://castlabs.com/">
              <img
                src="https://castlabs.com/wp-content/themes/wordpress-cl-theme/assets/castlabs-logo-eggshell.svg?no-inline"
                alt="Castlabs Logo"
                className={styles.bannerLogo}
              />
            </a>
          </div>
          <div className={styles.intro}>
            <p>
              Example Next.js 16 app with Castlabs
              <a
                href="https://demo.castlabs.com/"
                target="_blank"
                rel="noopener noreferrer"
              >
                PRESTOplay
              </a>
              player for web. All HTML including the video element, seek bar and
              video controls is rendered server side. Only the necessary components of the SDK are
              imported, and they are fetched from the server as a single chunk.
            </p>
            <p>
              <Link href="/detail">View Detail Page →</Link>
            </p>
          </div>
          <div className={styles.video}>
            <VideoPlayer />
          </div>
        </main>
      </div>
    </>
  );
}
